#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: params-ita-admin
  namespace: exastro-it-automation
data:
  LISTEN_PORT: "8080"
  STORAGEPATH: "/storage/"
  DEFAULT_LANGUAGE: "ja"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ita-api-admin
  namespace: exastro-it-automation
spec:
  selector:
    matchLabels:
      name: ita-api-admin
  replicas: 1
  template:
    metadata:
      labels:
        name: ita-api-admin
    spec:
      initContainers:
        # temporary response to organization_create_controller.py  organization_create, os.makedirs(organization_dir)
        - name: setup-storage
          command: ["sh", "-c", "chown -R 1000:1000 /storage "]
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /storage
            name: persistent-storage
      containers:
        - name: ita-api-admin
          image: exastro/it-automation2-test-ita-api-admin:Integration-test.13dc22.20221004-213256
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          envFrom:
            - secretRef:
                name: secret-ita-mariadb
            - secretRef:
                name: secret-ita-gitlab
            - configMapRef:
                name: params-ita-mariadb
            - configMapRef:
                name: params-ita-common
            - configMapRef:
                name: params-ita-gitlab
            - configMapRef:
                name: params-ita-admin
          volumeMounts:
            - name: persistent-storage
              mountPath: /storage
            - name: contaier-volume
              mountPath: /var/run_app_user/httpd/pid
              subPath: httpd-pid
            - name: contaier-volume
              mountPath: /var/run_app_user/httpd/socket
              subPath: httpd-socket
            - name: contaier-volume
              mountPath: /tmp
            - name: emptydir-vol
              mountPath: /home/app_user
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: ita-pvc
        - name: contaier-volume
          emptyDir: {}
        - name: emptydir-vol
          emptyDir: {}

