apiVersion: v1
kind: ConfigMap
metadata:
  name: params-ita-by-menu-create
  namespace: exastro-it-automation
data:
  EXECUTE_INTERVAL: "1"
  STORAGEPATH: /storage/
  CONTAINER_BASE: "kubernetes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ita-by-menu-create
  namespace: exastro-it-automation
spec:
  selector:
    matchLabels:
      name: ita-by-menu-create
  replicas: 1
  template:
    metadata:
      labels:
        name: ita-by-menu-create
    spec:
      containers:
        - name: ita-by-menu-create
          image: exastro/it-automation2-test-ita-by-menu-create:Integration-test.13dc22.20221004-213151
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     memory: "64Mi" #仮決め
          #     cpu: "250m"    #仮決め
          #   limits:
          #     memory: "64Mi" #仮決め
          #     cpu: "250m"    #仮決め
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          envFrom:
            - secretRef:
                name: secret-ita-mariadb
            - configMapRef:
                name: params-ita-mariadb
            - configMapRef:
                name: params-ita-common
            - configMapRef:
                name: params-ita-by-menu-create
          volumeMounts:
            - name: persistent-storage
              mountPath: /storage
            - name: contaier-volume
              mountPath: /tmp
            - name: emptydir-vol
              mountPath: /home/app_user
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: ita-pvc
        - name: contaier-volume
          emptyDir: {}
        - name: emptydir-vol
          emptyDir: {}

