{{- include "common.configmap" (list . "ita-api-admin.configmap") -}}
{{- define "ita-api-admin.configmap" -}}
metadata:
  labels:
    {{- include "ita-api-admin.labels" . | nindent 4 }}
data:
  DEFAULT_LANGUAGE: "{{ .Values.extraEnv.DEFAULT_LANGUAGE }}"
  LISTEN_PORT: "{{ .Values.extraEnv.LISTEN_PORT }}"  
  STORAGEPATH: "{{ .Values.persistence.mountPath.storage }}/"
{{- end -}}
{{- include "common.configmaps" . -}}