{{- include "common.secret" (list . "ita-api-admin.secret") -}}
{{- define "ita-api-admin.secret" -}}
metadata:
  labels:
    {{- include "ita-api-admin.labels" . | nindent 4 }}
data: {}
{{- end -}}
{{- include "common.secrets" . -}}