apiVersion: v1
kind: Service
metadata:
  name: {{ include "ita-api-admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ita-api-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "ita-api-admin.selectorLabels" . | nindent 4 }}
