{{/* Custom configMap */}}
{{- define "common.configmap.tpl" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: params-{{ template "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
data: {}
{{- end -}}

{{/* Custom Exastro IT Automation global config*/}}
{{- define "common.configmap.ita-global" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: params-{{ .Values.global.itaGlobalDefinition.name }}
  namespace: {{ .Release.Namespace }}
data: {{- toYaml .Values.global.itaGlobalDefinition.config | nindent 2 -}}
{{- end -}}

{{/* Custom Exastro IT Automation gitlab config */}}
{{- define "common.configmap.ita-gitlab" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: params-{{ .Values.global.gitlabDefinition.name }}
  namespace: {{ .Release.Namespace }}
data: {{- toYaml .Values.global.gitlabDefinition.config | nindent 2 -}}
{{- end -}}

{{/* Custom Exastro IT Automation MariaDB config */}}
{{- define "common.configmap.ita-mariadb" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: params-{{ .Values.global.databaseDefinition.name }}
  namespace: {{ .Release.Namespace }}
data: {{- toYaml .Values.global.databaseDefinition.config | nindent 2 -}}
{{- end -}}

{{/* Print Exastro IT Automation tool configMap */}}
{{- define "common.configmap" -}}
{{-   $top := first . -}}
{{-   include "common.util.merge" (append . "common.configmap.tpl") | nindent 0 -}}
{{- end -}}

{{/* Print Exastro IT Automation common configMaps */}}
{{- define "common.configmaps" -}}
{{-   if .Values.global.itaGlobalDefinition.enabled -}}
{{-     include "common.configmap.ita-global" . | nindent 0 -}}
{{-   end -}}
{{-   if .Values.global.gitlabDefinition.enabled -}}
{{-     include "common.configmap.ita-gitlab" . | nindent 0 -}}
{{-   end -}}
{{-   if .Values.global.databaseDefinition.enabled -}}
{{-     include "common.configmap.ita-mariadb" . | nindent 0  -}}
{{-   end -}}
{{- end -}}