{{/* Custom secret */}}
{{- define "common.secret.tpl" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ template "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data: {}
{{- end -}}

{{/* Custom Exastro IT Automation GitLab secrets */}}
{{- define "common.secret.ita-gitlab" -}}
{{- $gitlab_root_token := required "global.gitlabDefinition.secret.GITLAB_ROOT_TOKEN is required!" .Values.global.gitlabDefinition.secret.GITLAB_ROOT_TOKEN -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ .Values.global.gitlabDefinition.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  GITLAB_ROOT_TOKEN: {{ toYaml $gitlab_root_token | b64enc | quote }}
{{- end -}}

{{/* Custom Exastro IT Automation database secrets */}}
{{- define "common.secret.ita-mariadb" -}}
{{- $db_root_password := required "global.databaseDefinition.secret.DB_ROOT_PASSWORD is required!" .Values.global.databaseDefinition.secret.DB_ROOT_PASSWORD -}}
{{- $db_user := required "global.databaseDefinition.secret.DB_USER is required!" .Values.global.databaseDefinition.secret.DB_USER -}}
{{- $db_password := required "global.databaseDefinition.secret.DB_PASSWORD is required!" .Values.global.databaseDefinition.secret.DB_PASSWORD -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ .Values.global.databaseDefinition.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_ROOT_PASSWORD:  {{ toYaml $db_root_password | b64enc | quote }}
  DB_USER:  {{ toYaml $db_user | b64enc | quote }}
  DB_PASSWORD:  {{ toYaml $db_password | b64enc | quote }}
{{- end -}}

{{/* Print Exastro IT Automation tool secret */}}
{{- define "common.secret" -}}
{{-   $top := first . -}}
{{-   include "common.util.merge" (append . "common.secret.tpl") | nindent 0 -}}
{{- end -}}

{{/* Print Exastro IT Automation common secrets */}}
{{- define "common.secrets" -}}
{{-   $gitlab := default dict .Values.global.gitlabDefinition -}}
{{-   $database := default dict .Values.global.databaseDefinition -}}
{{-   if (default false $gitlab.enabled) -}}
{{-     include "common.secret.ita-gitlab" . | nindent 0 -}}
{{-   end -}}
{{-   if (default false $database.enabled) -}}
{{-     include "common.secret.ita-mariadb" . | nindent 0 -}}
{{-   end -}}
{{- end -}}