apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"  #仮決め
            cpu: "{{ .Values.resources.requests.cpu }}"  #仮決め
          #limits:
          #  memory: "{{ .Values.resources.limits.memory }}"  #仮決め
          #  cpu: "{{ .Values.resources.limits.cpu }}"  #仮決め
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        envFrom:
          - secretRef:
              name: {{ .Values.global.dbAccountInfo }}
          - configMapRef:
              name: {{ .Values.global.dbConnectionInfo }}
          - configMapRef:
               name: {{ .Values.global.itaBaseInfo }}
          - configMapRef:
               name: {{ .Values.global.itaByMenuCreateInfo }}
        volumeMounts:
          - name: persistent-storage
            mountPath: {{ .Values.volume.mountPath.name1 }}
            subPath:  {{ .Values.volume.mountPath.subPath1 }}
          - name: contaier-volume
            mountPath:  {{ .Values.volume.mountPath.name2 }}
          - name: emptydir-vol
            mountPath:  {{ .Values.volume.mountPath.name3 }}
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.global.claimName }}
      - name: contaier-volume
        emptyDir: {}
      - name: emptydir-vol
        emptyDir: {}
