apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }} 
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"  #仮決め
            cpu: "{{ .Values.resources.requests.cpu }}"  #仮決め
          #limits:
          #  memory: "{{ .Values.resources.limits.memory }}"  #仮決め
          #  cpu: "{{ .Values.resources.limits.cpu }}"  #仮決め
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        envFrom:
          - secretRef:
              name: {{ .Values.global.dbAccountInfo }}
          - configMapRef:
              name: {{ .Values.global.dbConnectionInfo }}
          - configMapRef:
               name: {{ .Values.global.itaBaseInfo }}
          - configMapRef:
               name: {{ .Values.global.itaByMenuCreateInfo }}
        volumeMounts:
          - name: ita-by-menu-storage
            mountPath: {{ .Values.volume.mountPath.storage }}
          - name: ita-by-menu-homedir
            mountPath: {{ .Values.volume.mountPath.homeDir }}
          - name: ita-by-menu-pid
            mountPath: {{ .Values.volume.mountPath.pid.path }}
            subPath: {{ .Values.volume.mountPath.pid.subPath }}
          - name: ita-by-menu-socket
            mountPath: {{ .Values.volume.mountPath.socket.path }}
            subPath: {{ .Values.volume.mountPath.socket.subPath }}
          - name: ita-by-menu-tmp
            mountPath: {{ .Values.volume.mountPath.tmp }}
      volumes:
        - name: ita-by-menu-storage
          persistentVolumeClaim:
            claimName: {{ .Values.global.claimName }}
        - name: ita-by-menu-homedir
          emptyDir: {}
        - name: ita-by-menu-pid
          emptyDir: {}
        - name: ita-by-menu-socket
          emptyDir: {}
        - name: ita-by-menu-tmp
          emptyDir: {}

