apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }} 
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.name }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: {{ .Values.service.portsName }}
    port: {{ .Values.service.portsNumber }}
    targetPort: {{ .Values.service.portsTargetNumber }}
  selector:
    name: {{ .Values.name }} 
