apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "ita-mariadb-setup-job.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec: 
  completions: {{ .Values.completionCount }}
  template: 
    spec:
      restartPolicy: "OnFailure"
      initContainers:
      - name: check-is-db-awake
        env:
          {{- range $define := .Values.global -}}
          {{-   range $config, $value := $define.config }}
          - name: {{ $config }}
            valueFrom:
              configMapKeyRef:
                name: params-{{ $define.name }}
                key: {{ $config }}
          {{-   end -}}
          {{-   range $secret, $value := $define.secret }}
          - name: {{ $secret }}
            valueFrom:
              secretKeyRef:
                name: secret-{{ $define.name }}
                key: {{ $secret }}
          {{-   end }}
          {{- end -}}
          {{ range $config, $value := .Values.extraEnv }}
          - name: {{ $config }}
            valueFrom:
              configMapKeyRef:
                name: params-{{ template "ita-mariadb-setup-job.fullname" $ }}
                key: {{ $config }}
          {{- end }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["sh", "-c"]
        args:
          - | {{ .Values.dbSetup.livenessCheck | nindent 12 }}
      containers: # we can have one or more containers
      - name: {{ template "ita-mariadb-setup-job.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["sh", "-c"]
        args:
          - | {{ .Values.dbSetup.createDBandTBL | nindent 12 }}
        ports:
          - containerPort: {{ .Values.global.databaseDefinition.config.DB_PORT }}
        env:
          {{- range $define := .Values.global -}}
          {{-   range $config, $value := $define.config }}
          - name: {{ $config }}
            valueFrom:
              configMapKeyRef:
                name: params-{{ $define.name }}
                key: {{ $config }}
          {{-   end -}}
          {{-   range $secret, $value := $define.secret }}
          - name: {{ $secret }}
            valueFrom:
              secretKeyRef:
                name: secret-{{ $define.name }}
                key: {{ $secret }}
          {{-   end }}
          {{- end -}}
          {{ range $config, $value := .Values.extraEnv }}
          - name: {{ $config }}
            valueFrom:
              configMapKeyRef:
                name: params-{{ template "ita-mariadb-setup-job.fullname" $ }}
                key: {{ $config }}
          {{- end }}
        resources: 
          {{- toYaml .Values.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
          - name: mysql-server-initdb
            mountPath: {{ .Values.volumeMounts.mountPath.createDB.path }}
            subPath: {{ .Values.volumeMounts.mountPath.createDB.subPath }}
          - name: mysql-server-conf
            mountPath: {{ .Values.volumeMounts.mountPath.conf.path }}
      volumes:
        - name: mysql-server-initdb
          configMap:
            name: mysql-server-initdb-config-setup
            items:
            - key: {{ .Values.volumeMounts.mountPath.createDB.subPath }}
              path: {{ .Values.volumeMounts.mountPath.createDB.subPath }}
              mode: 0644            
        - name: mysql-server-conf
          configMap:
            name: mysql-server-conf-config-setup