#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
# {{ image }} {{ image_tag }} {{ param01 }} {{ param02 }} {{ param03 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-server-initdb-config
  namespace: exastro-it-automation
data:
  createdb.sql: |
    CREATE DATABASE IF NOT EXISTS ITA_DB;
    CREATE TABLE IF NOT EXISTS `ITA_DB`.`T_COMN_ORGANIZATION_DB_INFO`
    (
        PRIMARY_KEY                     VARCHAR(40),                                -- 主キー
        ORGANIZATION_ID                 VARCHAR(255),                               -- organizationのID
        DB_HOST                         VARCHAR(255),                               -- DBホスト
        DB_PORT                         INT,                                        -- DBポート
        DB_DATADBASE                    VARCHAR(255),                               -- DBDB名
        DB_USER                         VARCHAR(255),                               -- DBユーザ
        DB_PASSWORD                     VARCHAR(255),                               -- DBパスワード
        DB_ROOT_PASSWORD                VARCHAR(255),                               -- DBRootパスワード
        GITLAB_USER                     VARCHAR(255),                               -- GitLabユーザ
        GITLAB_TOKEN                    VARCHAR(255),                               -- GitLabトークン
        NOTE                            TEXT,                                       -- 備考
        DISUSE_FLAG                     VARCHAR(1)  ,                               -- 廃止フラグ
        LAST_UPDATE_TIMESTAMP           DATETIME(6),                                -- 最終更新日時
        LAST_UPDATE_USER                VARCHAR(40),                                -- 最終更新者
        PRIMARY KEY(PRIMARY_KEY)
    )ENGINE = InnoDB, CHARSET = utf8mb4, COLLATE = utf8mb4_bin, ROW_FORMAT=COMPRESSED ,KEY_BLOCK_SIZE=8;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-server-conf-config
  namespace: exastro-it-automation
data:
  custom.cnf: |
    [mysqld]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: params-ita-mariadb
  namespace: exastro-it-automation
data:
  DB_HOST: "ita-mariadb.exastro-it-automation.svc"
  DB_PORT: "3306"
  DB_DATADBASE: "ITA_DB"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ita-mariadb
  labels:
    app: mariadb # service will look for this label
  namespace: exastro-it-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for pods
      containers: # we can have one or more containers
        - name: mariadb
          image: mariadb:10.9
          ports:
            - containerPort: 3306
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: params-ita-common
                  key: TZ
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "0" # if it is 1 and root_password is set, root_password takes precedance
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-ita-mariadb
                  key: DB_ROOT_PASSWORD
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-ita-mariadb
                  key: DB_PASSWORD
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: secret-ita-mariadb
                  key: DB_USER
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: params-ita-mariadb
                  key: DB_DATADBASE
          securityContext:
            allowPrivilegeEscalation: true
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            seLinuxOptions: {}
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-server-initdb
              mountPath: /docker-entrypoint-initdb.d/createdb.sql
              #subPath: docker-entrypoint-initdb.d
              subPath: createdb.sql
            - name: mysql-server-conf
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: ita-mariadb
        - name: mysql-server-initdb
          configMap:
            name: mysql-server-initdb-config
        - name: mysql-server-conf
          configMap:
            name: mysql-server-conf-config
